### ISSUE TITLE
一种更逆天的课表格式

### ISSUE THREAD

**Issue by pizeroLOL** [SmartTeachCN/CSES#12]
核心想法：
 
把从 `start` 开始的时间当成一条环状的绳子，从 `start` 定义的时间开始根据 `schedules` 中定义的 `subject_id` 查找 `subject` 的 `dur` 字段。

```yaml
...
start: 2025-01-13T00:00:00+08:00 # 开始时间
subjects: # 课程
  sleep: # 课程id
    dur: 07:00:00 # 课程持续时间
    ...
  eat:
    dur: 01:00:00
    ...
schedules: # 课程安排
- sleep # 课程 id
- eat
```

如上所示，我们构建了一个由 `eat` 和 `sleep` 组成的吃睡循环，他从 `start` 所表示 2025 年 1 月 13 日开始，没有结束时间。

第一次睡由 `start` 开始，到 `start` + `sleep.dur` 这一瞬间前结束，也就是从 2025 年 1 月 13 日 0 点开始，睡到 2025 年 1 月 13 日 7 点，用区间表达就是 `[2025-01-13T00:00:00+08:00, 2025-01-13T08:00:00+08:00)`。

然后吃一小时，也就是 `[2025-01-13T08:00:00+08:00, 2025-01-13T09:00:00+08:00)`。

接下来继续睡 `[2025-01-13T09:00:00+08:00, 2025-01-13T16:00:00+08:00)`，继续吃，以此类推。

然后加入：
- 全称 `full_name`
- 简称 `simplified_name`
- 是否为课程 `is_class`

可选拓展：
- 老师 `teacher`
- 教室 `room`

以及加入各种以 string 为 key，以 `true | false | string | int | float | datetime | time | date` 为 value 的各种自定义拓展字段。

注意，这里的 key不能冲突，冲突报错，subject_id 同理。

<details><summary>单周课表样式</summary>
<p>

```yaml
version: 2
start: 2025-01-13T00:00:00+08:00
subjects:
  math:
    simplified_name: M
    full_name: Math
    teacher: Mr. A
    is_class: true
    room: '101'
    dur: 00:40:00
  english:
    simplified_name: E
    full_name: English
    teacher: Mr. B
    is_class: true
    room: '102'
    dur: 00:40:00
  physics:
    simplified_name: P
    full_name: Math
    teacher: Mr. C
    is_class: true
    room: 103
    dur: 00:40:00
  gap:
    simplified_name: G
    full_name: Gap
    is_class: false
    dur: 00:10:00
  big_gap:
    simplified_name: B
    full_name: 大课间
    is_class: true
    dur: 00:30:00
  prepare:
    full_name: 无课
    is_class: false
    dur: 08:00:00
  mid_gap:
    full_name: 午休
    is_class: false
    dur: 02:00:00
  finish:
    full_name: 放学
    is_class: false
    dur: 09:10:00
  no_class:
    full_name: 无课
    is_class: false
    dur: 24:00:00
schedules:
- prepare # 8:00
- math # 8:40
- gap # 8:50
- math # 9:30
- big_gap # 10:00
- english # 10:40
- gap # 10:50
- english # 11:30
- mid_gap # 13:30
- physics # 14:10
- gap # 14:20
- physics # 14:50
- finish # 00:00

- prepare # 8:00
- math # 8:40
- gap # 8:50
- math # 9:30
- big_gap # 10:00
- english # 10:40
- gap # 10:50
- english # 11:30
- mid_gap # 13:30
- physics # 14:10
- gap # 14:20
- physics # 14:50
- finish # 00:00


- prepare # 8:00
- math # 8:40
- gap # 8:50
- math # 9:30
- big_gap # 10:00
- english # 10:40
- gap # 10:50
- english # 11:30
- mid_gap # 13:30
- physics # 14:10
- gap # 14:20
- physics # 14:50
- finish # 00:00

- prepare # 8:00
- math # 8:40
- gap # 8:50
- math # 9:30
- big_gap # 10:00
- english # 10:40
- gap # 10:50
- english # 11:30
- mid_gap # 13:30
- physics # 14:10
- gap # 14:20
- physics # 14:50
- finish # 00:00

- prepare # 8:00
- math # 8:40
- gap # 8:50
- math # 9:30
- big_gap # 10:00
- english # 10:40
- gap # 10:50
- english # 11:30
- mid_gap # 13:30
- physics # 14:10
- gap # 14:20
- physics # 14:50
- finish # 00:00

- no_class
- no_class
```

</p>
</details> 

<details><summary>scheme</summary>
<p>

```yaml
datetime: yyyy-mm-ddTHH:MM:SS+oY:oM # 2025-2-1T02:22:24+08:00
date: yyyy-mm-dd
time: HH:MM:SS # 08:10:00
subject: 
  [subject_id: string]:
    is_class: true | false
    full_name: string
    dur: time
    simplified_name: char | null
    room: string | null
    teacher: string | null
    [item: string]: true | false | string | int | float | datetime | time | date # 各客户端的拓展标准
root:
  version: 2
  start: datetime
  subjects: subject[]
  schedules: subject_id[]
```

</p>
</details>

**Comment by DryIce-cc** [comment]
在逆天中整出合理性又何尝不是一种成功。
~[Close as not planned]~

**Comment by RinLit-233-shiroko** [comment]
> ❤️ Love from [Deepseek](https://chat.deepseek.com/)

## 优点
- **结构清晰**

  配置文件采用 YAML 格式，层次分明，易于阅读和编写。
  
  顶层字段（`version`、`start`、`subjects`、`schedules`）分工明确，逻辑清晰。

- **灵活性高**

  课程定义灵活：每个课程可以定义多个字段（如 `full_name`、`simplified_name`、`teacher`、`room `等），并支持自定义扩展字段。
  
  时间计算简单：通过 start 和 dur 字段，可以轻松计算每个课程的时间区间。
  
  支持无限循环：通过 schedules 的循环设计，课表可以无限重复，适合长期使用。
  
- **扩展性强**

  支持自定义字段，允许不同客户端根据需求扩展功能（如添加 `color`、`priority `等字段）。
  
  课程类型区分明确（`is_class `字段），便于区分正式课程和非课程活动（如午休、放学）。

- 时间处理规范

  使用 ISO 8601 标准的时间格式（如 2025-01-13T00:00:00+08:00），支持时区，适合国际化场景。
  
  时间区间采用左闭右开（`[start, end]`），符合编程和数学中的常见规范。

- 支持复杂场景

  可以定义全天无课（`no_class`）、跨天课程等特殊场景。
  
  通过 schedules 的列表结构，可以轻松定义单日或多日的课程安排。

<hr>

## 缺点
- **重复性较高**

  在 `schedules `中，每天的课程安排需要重复列出，导致配置文件冗长。例如，周一到周五的课程安排完全相同时，仍需重复 5 次。
  
  改进建议：引入“模板”机制，支持定义通用模板并引用，减少重复代码。

- **跨天处理不够直观**

  虽然支持跨天课程，但对于初学者来说，跨天的时间计算可能不够直观。
  
  改进建议：在文档中提供跨天计算的示例，或增加工具函数帮助计算。

- **缺少对节假日的支持**

  目前的设计没有考虑节假日或特殊日期的课程调整。
  
  改进建议：增加 `exceptions `字段，支持定义特定日期的特殊安排。

- **时间计算依赖手动**

  每个课程的时间区间需要手动计算，容易出错。
  
  改进建议：提供工具或脚本，自动生成时间区间并验证逻辑。

- **字段冲突处理不够明确**

  虽然提到字段冲突会报错，但未明确冲突时的具体处理方式（如覆盖、忽略或报错）。
  
  改进建议：在文档中明确冲突处理规则。

- **缺少对多语言的支持**

  `full_name `等字段仅支持单一语言，不适合国际化场景。
  
  改进建议：支持多语言字段，如 `full_name_en`、`full_name_zh`。

## 改进建议
- **引入模板机制**

定义通用模板，减少重复代码。例如：

```
templates:
  weekday:
    - prepare
    - math
    - gap
    - ...
schedules:
  - template: weekday
  - template: weekday
  - [no_class]
```

- **增加节假日支持**

添加 exceptions 字段，支持特殊日期的课程调整。例如：

```
exceptions:
  2025-01-01: [holiday]  # 元旦全天放假
  2025-02-10: [prepare, math, ...]  # 特殊安排
```

- **提供时间计算工具**

开发工具或脚本，自动计算课程时间区间并验证逻辑。

- **支持多语言**

为 full_name 等字段增加多语言支持。例如：

```
full_name:
  en: Math
  zh: 数学
```

- **明确字段冲突规则**

在文档中明确字段冲突时的处理方式，如“覆盖”、“忽略”或“报错”。

<hr>

## 总结
这个课表格式设计得非常优秀，适合大多数周期性课程安排场景。它的清晰性、灵活性和扩展性是其最大亮点，但在重复性、跨天处理、节假日支持等方面仍有改进空间。通过引入模板机制、节假日支持和多语言功能，可以进一步提升其适用性和易用性。
