### ISSUE TITLE
考虑一下多周轮换

### ISSUE THREAD

**Issue by pizeroLOL** [SmartTeachCN/CSES#17]
week_type 可以考虑改成这样（？）：

``` yml
week_div: 1  # 多周轮换对应的周数
week_total: 2  # 总共轮换的周数
```

这样对有多周轮换的软件会更友好一些。同时可能还要考虑不自动启用的课表的兼容问题。

_最初由 HelloWRC 在 https://github.com/SmartTeachCN/CSES/issues/1#issuecomment-2628964737 发布_

**Comment by pizeroLOL** [comment]
或者说变为

```
schedules:
- mon:
  - subjects: aaa
    start_time: 04:00:00
    end_time: 06:00:00
 - subject: bbb
    ...
```

其中星期可以参考 #1 我写的相关缩写或者全小写全拼，如果能保证各平台一致性的话用数字或者字符串的 1-7 或者 0-6 也可以
