### ISSUE TITLE
找人锐评一下这个逆天配置文件

### ISSUE THREAD

**Issue by pizeroLOL** [SmartTeachCN/CSES#21]
```yaml
version: 2
start: 2025/3/29
subjects:
  chinese:
    name: 语文
    room: "404"
    teacher: 林老师
    short_name: 语
    pre_exec: "path/to/file"
    post_exec: "path/to/file"
  build_network:
    name: 路由交换配置
  default:
    name: 下课
schedules:
  - "1":
      - subject: chinese
        start: "08:00:00"
        end: "09:00:00"
        pre_exec: "path/to/file"
        post_exec: "path/to/file"
    "7":
      - subject: build_network
        start: "10:00:00"
        end: "11:00:00"
  - "7":
      - subject: build_network
        start: "10:00:00"
        end: "11:00:00"
```
