### ISSUE TITLE
新规范文档提议

### ISSUE THREAD

**Issue by Mike-Luo-Leap** [SmartTeachCN/CSES#6]
# CSES 规范文档

## 先决条件
- 必须采用 UTF-8 编码
- 只能采用空格缩进，不允许使用制表符
- 文件开头要有标识符

## 标识符

```yaml
!Data
Name: # 课表名称
Type: CSES
Version: # 采用的 CSES 版本
```

## 课程声明

```yaml
Subjects:
    - Name: 语文
      SimplifiedName: 语 # Optional
      Teacher: Mr. A # Optional
      Room: 101 # Optional
      IsOutDoorClass: false # Optional, default. false
    - Name: 数学
```

## 时间线声明

```yaml
TimeTable:
    - Id: # 编号，非可选
    - Name: 
    - TimeZone: # Optional, default. UTC+08:00
    - WeekDiv: # int, Optional，舍弃WeekTotal，根据WeekDiv自动读取，要求WeekDiv必须连续
    - TimeSlot:
        - Name: 
          Id: # 非可选
          Type: # 待定，如早读、晚自习之类的玩意，非可选
          StartTime: "hh:mm:ss"
          EndTime: "hh:mm:ss"
    - TimeSlot: 
        # ...
```

## 课表安排
```yaml
Schedule:
    - Name: "Monday" # string
      TimeTable: # int
      EnableDay: 1
      Classes:
        - Subject:
          TimeSlot: #int
        - Subject:
          TimeSlot:
    - Name: "Tuesday"
```
